---

name: 'Tag'

"on":
    push:
      branches:
        - 'main'

permissions:
    contents: 'write'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v4.1.1
            with:
                fetch-tags: true
                fetch-depth: 0

          - name: 'Install Go for the release'
            uses: actions/setup-go@v5
            with:
              go-version: '^1.21.0'

          - name: 'Generate Release'
            env:
                GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                GPG_PRIVATE_KEY: '${{ secrets.GPG_PRIVATE_KEY }}'
                GPG_SIGNING_KEY_ID: '${{ secrets.GPG_SIGNING_KEY_ID }}'
            run: |
                make release
